### Creats a new patient entoty
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Abutex Limiteds",
  "email": "abutexlimited17@gmail.com",
  "address": "125 Bishop Johnson stress Town",
  "dateOfBirth": "1984-05-15",
  "registeredDate": "2013-07-11"

}

###